version: "3"

services:
  # auth-service:
  #   build:
  #     context: ../auth-service
  #     dockerfile: auth-service.dockerfile
  #   container_name: auth-service
  #   ports:
  #     - "8088:8080"
  #   volumes:
  #     - ../auth-service:/app
  #   environment:
  #     - GIN_MODE=debug
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
